name: Build and push containers
on:
    workflow_call:
        inputs:
            image-tag:
                required: true
                type: string
            image-php-target:
                required: true
                type: string
        secrets:
            dockerUser:
                required: true
            dockerPassword:
                required: true
jobs:
    build-webserver:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup build
                uses: ./.github/actions/setup-build
                with:
                    docker-user: ${{ secrets.dockerUser }}
                    docker-password: ${{ secrets.dockerPassword }}
            -   name: Build auth-php and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    file: docker/nginx/Dockerfile
                    tags: dzhuryn/ticketing-auth-webserver:${{ inputs.image-tag }}
    build-php:
        needs: build-webserver
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup build
                uses: ./.github/actions/setup-build
                with:
                    docker-user: ${{ secrets.dockerUser }}
                    docker-password: ${{ secrets.dockerPassword }}
            -   name: Build auth-php and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    target: ${{ inputs.image-php-target }}
                    file: docker/php/Dockerfile
                    tags: dzhuryn/ticketing-auth-php:${{ inputs.image-tag }}
    build-jobber:
        needs: build-php
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup build
                uses: ./.github/actions/setup-build
                with:
                    docker-user: ${{ secrets.dockerUser }}
                    docker-password: ${{ secrets.dockerPassword }}
            -   name: Build auth-php and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    file: docker/jobber/Dockerfile
                    tags: dzhuryn/ticketing-auth-jobber:${{ inputs.image-tag }}