name: Deploy to dev workfow
on: workflow_dispatch
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Log in to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USER }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
                with:
                    version: "lab:latest"
                    driver: cloud
                    endpoint: "dzhuryn/default"
                    install: true
            -   name: Build and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    file: docker/nginx/Dockerfile
                    tags: dzhuryn/ticketing-auth-webserver:latest
                    platforms: linux/amd64