name: Deploy to prod env
on:
    push:
        branches:
            - main
jobs:
    discover-tag:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   uses: oprypin/find-latest-tag@v1
                with:
                    repository: dzhuryn97/ticketing-auth
                id: tag-discover
            -   run: echo "Tag is at version ${{ steps.tag-discover.outputs.tag }}"
        outputs:
            tag: ${{ steps.tag-discover.outputs.tag }}
    build:
        needs: discover-tag
        uses: ./.github/workflows/build.yml
        with:
            image-tag: ${{ needs.discover-tag.outputs.tag }}
            image-php-target: prod
        secrets:
            dockerUser: ${{ secrets.DOCKER_USER }}
            dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: ssh key passphrase
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USERNAME }}
                    key: ${{ secrets.SERVER_KEY }}
                    debug: true
                    script: |
                        cd /var/www/ticketing
                        echo "Tag ${{ needs.discover-tag.outputs.tag }}"
                        sed -i 's/^SERVICE_AUTH_VERSION=.*/SERVICE_AUTH_VERSION=${{ needs.discover-tag.outputs.tag }}/' .env
                        docker compose up -d
                        docker compose exec auth_php bin/console doctrine:migrations:migrate --no-interaction