name: Deploy to dev env
on:
    push:
        branches:
            - dev
jobs:
    build-webserver:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup build
                uses: ./.github/actions/setup-build
                with:
                    docker-user: ${{ secrets.DOCKER_USER }}
                    docker-password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Build auth-php and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    file: docker/nginx/Dockerfile
                    tags: dzhuryn/ticketing-auth-webserver:latest
    build-php:
        needs: build-webserver
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup build
                uses: ./.github/actions/setup-build
                with:
                    docker-user: ${{ secrets.DOCKER_USER }}
                    docker-password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Build auth-php and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    file: docker/php/Dockerfile
                    tags: dzhuryn/ticketing-auth-php:latest
    build-jobber:
        needs: build-php
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup build
                uses: ./.github/actions/setup-build
                with:
                    docker-user: ${{ secrets.DOCKER_USER }}
                    docker-password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Build auth-php and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    file: docker/jobber/Dockerfile
                    tags: dzhuryn/ticketing-auth-jobber:latest

    deploy:
        needs: build-jobber
        runs-on: ubuntu-latest
        steps:
            -   name: ssh key passphrase
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USERNAME }}
                    key: ${{ secrets.SERVER_KEY }}
                    debug: true
                    script: |
                        cd /var/www/ticketing
                        docker image pull dzhuryn/ticketing-auth-webserver:dev-#hash
                        docker compose up -d --force-recreate